version: '3'

networks:
  app-tier:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres